### PR TITLE
Pooja yadav

### PR DESCRIPTION
**Pull request by Pooja2398**
Assignment1

### CODE REVIEW

**Comment by AKSHAYA-SANAL** [comment]
your file is blank

**Comment by Pooja2398** [comment]
after that i pulled another file ....

**Comment by Pooja2398** [comment]
Please revert me if the if it's still blank

**Comment by AKSHAYA-SANAL** [comment]
Yes, it is still blank
Can I reopen the pull request you gave earlier and merge it. The code looks fine

**Comment by Pooja2398** [comment]
OKAY I WILL DO

**Comment by Pooja2398** [comment]
I opened that pull request

**Pull request closed without merging**
