### PR TITLE
Merge branch 'AKSHAYA-SANAL:main' into main

### PR DESCRIPTION
**Pull request by Pooja2398**

### CODE REVIEW

**Comment by AKSHAYA-SANAL** [comment]
Finally you made it :)

**Comment by Pooja2398** [comment]
Yes finally !!

**Comment by AKSHAYA-SANAL** [comment]
And the page is AWESOME.... It looks professional and is interactive. The fading effect at the skills section was really nice and keep practicing....All the best..

**Comment by Pooja2398** [comment]
Thank you so much ....
Thankyou for the feedback!

**Pull request merged**
