### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by Pooja2398**
fig4
fig

### CODE REVIEW

**Comment by AKSHAYA-SANAL** [comment]
Pooja your code is very clean and the form looks good. 
1. Add your css inside the style tag within head or create style.css inside you folder, then you will have to give me 2 PRs.
2. Add Date, Phonenumber, Email inputs, checkbox, and add atleast 1 pseudo class

**Comment by Pooja2398** [comment]
Okay

**Comment by AKSHAYA-SANAL** [comment]
I'm closing this PR, give another one after completing :)

**Comment by Pooja2398** [comment]
Alright

**Pull request closed without merging**
